r"""
@File       : l1_fundamental_detection.py
@Author     : Chengjuan Wan, et al.
@Institution: University of Chinese Academy of Sciences
@Description:
    Stage 1: Fundamental Detection (L1) module for the WH-DRCS ISAC framework.
    This module ingests raw Range-Doppler-Angle (RDA) JSON data generated by
    the NIST ISAC-PLM (IEEE 802.11ay/bf EDMG mode) platform, executes clutter
    suppression, and extracts multi-dimensional kinematic metrics (Reflection
    Entropy, Spatial-Temporal Smoothness, and Acceleration Limits) to evaluate
    the fundamental detection confidence.
"""

import json
import numpy as np
from scipy.linalg import norm
from typing import List, Dict, Tuple, Optional, Any


class ISACPLM_DataParser:
    r"""
    Parser for handling high-precision discrete delay-Doppler matrix outputs
    from the NIST ISAC-PLM software.
    """

    def __init__(self, filepath: str):
        self.filepath = filepath
        self.raw_data = self._load_json()

    def _load_json(self) -> List[Dict[str, Any]]:
        """Safely loads the continuous JSON stream produced by the platform."""
        parsed_data = []
        try:
            with open(self.filepath, 'r') as file:
                for line in file:
                    if line.strip():
                        parsed_data.append(json.loads(line))
        except FileNotFoundError:
            raise FileNotFoundError(f"[Error] ISAC-PLM output {self.filepath} not found.")
        return parsed_data

    def extract_kinematic_sequence(self, target_id: int = 0) -> Dict[str, np.ndarray]:
        """
        Extracts the kinematics K = {(v_t, r_t)}_{t=1}^T and corresponding
        reflection power after the 2D extremum search on the interference-free matrix.
        """
        velocities, ranges, powers = [], [], []

        for entry in self.raw_data:
            # Assuming 'axisVelocity', 'range', 'reflectionPower' keys exist in NIST JSON
            if 'axisVelocity' in entry and 'reflectionPower' in entry:
                velocities.append(np.mean(entry['axisVelocity']))
                ranges.append(np.mean(entry.get('range', [0.0])))
                powers.append(np.mean(entry['reflectionPower']))

        return {
            'velocity': np.array(velocities, dtype=np.float64),
            'range': np.array(ranges, dtype=np.float64),
            'power': np.array(powers, dtype=np.float64)
        }


class L1_FundamentalDetector:
    r"""
    Implements Stage 1 of the Hierarchical Signal Processing Algorithm.
    Evaluates target existence probability by fusing multi-dimensional
    metrics via an adaptive covariance-based confidence function.
    """

    def __init__(self, pri_duration: float = 50.00e-6, gamma_detect: float = 0.85, eta_a: float = 15.0):
        r"""
        :param pri_duration: Pulse Repetition Interval (T_PRI) in seconds.
        :param gamma_detect: Detection confidence threshold (\gamma_{detect}).
        :param eta_a: Maximum physically feasible acceleration (\eta_a) in m/s^2.
        r"""
        self.T_PRI = pri_duration
        self.gamma_detect = gamma_detect
        self.eta_a = eta_a

        # Frozen calibration covariance for metric normalization (S_v, S_r, H_p).
        # It is estimated on the training partition and is not updated at test time.
        self._metric_covariance = np.diag([0.05, 0.02, 0.1])

    def _compute_reflection_entropy(self, power_spectrum: np.ndarray) -> float:
        r"""
        Computes the Reflection Entropy (\mathcal{H}_p) to quantify energy concentration.
        A lower true Shannon entropy implies higher concentration (target presence).
        Outputs a normalized metric \in [0, 1].
        r"""
        if len(power_spectrum) <= 1:
            return 0.0

        # Normalize power to represent a probability mass function (PMF)
        p = np.abs(power_spectrum) / np.sum(np.abs(power_spectrum) + 1e-12)
        p = p[p > 0]  # Filter out zero probabilities to avoid log(0)

        shannon_entropy = -np.sum(p * np.log(p))
        max_entropy = np.log(len(power_spectrum))

        # Invert and normalize: 1.0 means perfectly concentrated (ideal target)
        return 1.0 - (shannon_entropy / max_entropy) if max_entropy > 0 else 1.0

    def _compute_kinematic_smoothness(self, sequence: np.ndarray) -> float:
        r"""
        Evaluates sequence smoothness (S_v, S_r) using second-order finite differences.
        Suppresses the impact of high-frequency AWGN and minor clutter fluctuations.
        r"""
        if len(sequence) < 3:
            return 1.0

        # Construct the second-order difference operator matrix
        N = len(sequence)
        D2 = np.eye(N) - 2 * np.eye(N, k=1) + np.eye(N, k=2)
        D2 = D2[:-2, :]  # Truncate invalid boundary rows

        # Compute the Frobenius norm of the second-order derivative
        roughness = norm(D2 @ sequence, ord=2) / np.sqrt(N)

        # Map roughness to a [0, 1] smoothness confidence score
        sigma_scale = 2.0
        return np.exp(- (roughness ** 2) / (2 * sigma_scale ** 2))

    def _extract_acceleration_bound(self, velocity_seq: np.ndarray) -> float:
        """
        Calculates the maximum discrete acceleration a_t.
        Violations of physical kinematic constraints indicate clutter or ghost targets.
        """
        if len(velocity_seq) < 2:
            return 0.0

        # Central difference for internal nodes, forward/backward for boundaries
        dv = np.gradient(velocity_seq)
        accelerations = np.abs(dv / self.T_PRI)
        return float(np.max(accelerations))

    def _adaptive_confidence_fusion(self, S_v: float, S_r: float, H_p: float) -> float:
        r"""
        Calculates the joint fundamental detection confidence \mathcal{C}_{L_1}.
        Replaces heuristic weight vectors with an Inverse-Variance Weighting (IVW) scheme.
        \mathcal{C}_{L_1} \leftarrow \mathbf{w}_1^T [S_v, S_r, \mathcal{H}_p]^T
        """
        metrics = np.array([S_v, S_r, H_p])

        # Calculate adaptive weights based on the inverse of the covariance trace
        inv_vars = 1.0 / np.diag(self._metric_covariance)
        w1 = inv_vars / np.sum(inv_vars)

        confidence = float(np.dot(w1, metrics))
        return np.clip(confidence, 0.0, 1.0)

    def execute_stage_1(self, kinematics: Dict[str, np.ndarray]) -> Tuple[bool, Optional[Dict[str, Any]]]:
        r"""
        Executes Stage 1: Fundamental Detection.
        :param kinematics: Extracted \mathcal{K} = {(v_t, r_t)}_{t=1}^T matrix.
        :return: (Detection Boolean, Hierarchical Semantic Output)
        """
        v_seq = kinematics.get('velocity', np.array([]))
        r_seq = kinematics.get('range', np.array([]))
        p_seq = kinematics.get('power', np.array([]))

        if len(v_seq) == 0:
            return False, {"Status": "Insufficient Data"}

        # 1. Compute multi-dimensional metrics
        H_p = self._compute_reflection_entropy(p_seq)
        S_v = self._compute_kinematic_smoothness(v_seq)
        S_r = self._compute_kinematic_smoothness(r_seq)
        a_t = self._extract_acceleration_bound(v_seq)

        # 2. Evaluate fundamental detection confidence
        C_L1 = self._adaptive_confidence_fusion(S_v, S_r, H_p)

        # 3. Apply decision logic (Algorithm 1, Lines 6-7)
        if C_L1 < self.gamma_detect or a_t > self.eta_a:
            return False, {
                "Status": "False Alarm (Clutter)",
                "Metrics": {"C_L1": C_L1, "a_t": a_t}
            }

        # 4. Target verified
        target_state_S = {
            "Status": "Target Detected",
            "C_L1_Confidence": round(C_L1, 4),
            "Metrics": {
                "H_p": round(H_p, 4),
                "S_v": round(S_v, 4),
                "S_r": round(S_r, 4),
                "Max_Accel": round(a_t, 4)
            },
            "Mean_Velocity": round(np.mean(v_seq), 4),
            "Mean_Range": round(np.mean(r_seq), 4)
        }

        return True, target_state_S


if __name__ == "__main__":
    # Example execution pipeline demonstrating integration with ISAC-PLM JSON output
    # (In actual deployment, 'rda.json' generated by NIST ISAC-PLM is required)

    try:
        # Step A: Ingest standard compliant JSON data
        parser = ISACPLM_DataParser(filepath="data/rda.json")
        kinematics_data = parser.extract_kinematic_sequence()

        # Step B: Initialize L1 Fundamental Detector
        # Using typical T_PRI for the L1 configuration (M=8)
        detector_l1 = L1_FundamentalDetector(pri_duration=50.00e-6, gamma_detect=0.85)

        # Step C: Execute unified detection
        is_target, semantic_output = detector_l1.execute_stage_1(kinematics_data)

        print(f"=== L1 Fundamental Detection Output ===")
        print(json.dumps(semantic_output, indent=4))

    except FileNotFoundError as e:
        print(f"Deployment Note: {e} Please ensure NIST ISAC-PLM simulation output is present in the directory.")
